### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by eyalFischel** [eyalFischel/SmartSaver#1]
Create a basic CONTRIBUTING.md for the project.

**Comment by MetroCat69** [comment]
You need to give more time for the project to mature

**Comment by eyalFischel** [comment]
I believe you are correct. However, creating a basic structure and starting development, whether alone or with a team, will help push the project towards maturity.
So created a basic CONTRIBUTING.md for now.

**Comment by MetroCat69** [comment]
see merge request

**Comment by eyalFischel** [comment]
We may need to change the license to MIT.

**Comment by MetroCat69** [comment]
this is for another issue

**Comment by MetroCat69** [comment]
can you close this issue?
