### ISSUE TITLE
Update the readme.md - update the Design.

### ISSUE THREAD

**Issue by eyalFischel** [eyalFischel/SmartSaver#2]
Suggest some basic architecture and update it on the repo and readme.

**Comment by MetroCat69** [comment]
I think we should add redis as a caching layer

**Comment by eyalFischel** [comment]
I think you are right.

**Comment by MetroCat69** [comment]
Do you think we will need an extensiveness full text search?

if so adding elastic search is a classic 

but this maybe be just over engineering stuff

**Comment by eyalFischel** [comment]
I think it will be over-engineering. 
Think about it , it's going to start as a simple budget management app, its not going to have too much for elastic.

**Comment by MetroCat69** [comment]
see readme
