### ISSUE TITLE
Mono repo?

### ISSUE THREAD

**Issue by MetroCat69** [eyalFischel/SmartSaver#9]
should we do a mono repo? shouldnt we do multi repo here?

**Comment by MetroCat69** [comment]
I am saying maybe we should do one repo for front and one repo for back

**Comment by eyalFischel** [comment]
Yeah, I understand. 
However, it seems much easier to wrap everything around Dockers and Docker-compose (maybe even k3s soon) -> test using GitLab CI/CD -> and push for deployment on a server. 
Using two repositories for each service may create some difficulties in testing the front-end against the back-end if one or the other changes (in my opinion).
Anyway, lets start and change the structure if needed.
